# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: Dockerfile


tasks:
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
  - init: poetry env use python && poetry install

