# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: Dockerfile


tasks:
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
  - init: poetry config virtualenvs.create true && poetry config virtualenvs.in-project true && poetry env use python && poetry install

